services:
  db:
    image: postgres:15
    restart: always
    container_name: e_store_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  server:
    build: .
    depends_on:
      - db
    ports:
      - "3500:3500"
    container_name: e_store_server
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && node app.js"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server    

volumes:
  pgdata:
