export const CREATE_ORDER_PENDING = "CREATE_ORDER_PENDING";

export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";

export const VERIFY_ORDER_SUCCESS = "VERIFY_ORDER_SUCCESS";

export const SET_ACTIVE_STEP = "SET_ACTIVE_STEP";
